### ISSUE TITLE
Update record failed AttributeError: 'RequestBuilder' object has no attribute 'eq'

### ISSUE THREAD

**Issue by pvbhanuteja** [supabase-community/supabase-py#12]
# Bug report
Tried installing locally looks there is some issue postgrest-py 

When I tried updating a record it's throwing up this error 

AttributeError: 'RequestBuilder' object has no attribute 'eq'

**Comment by taloglu** [comment]
I experience the same issue.

**Comment by abreumatheus** [comment]
It can be a syntax error, since this project is not yet fully documented.

This is the correct syntax for using `eq` and other operations:
`supabase_client.from_("table_name").select("*").eq("column_name", "value").execute()`
or
`supabase_client.table("table_name").select("*").eq("column_name", "value").execute()`

**Comment by J0** [comment]
Hey @pvbhanuteja,

Thanks for reporting this issue! We tried it and it seems like 
`supabase_client.table("table_name").select("*").eq("column_name", "value").execute()`
is functioning. We'll be closing this for now but let us know if you run into any further issues.

![image](https://user-images.githubusercontent.com/8011761/139557604-a3a05810-6835-44d6-a988-f2736489e1bd.png)
