### ISSUE TITLE
can you update these dependency

### ISSUE THREAD

**Issue by wanghaisheng** [supabase-community/supabase-py#212]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

supabase-py 0.0.2 requires gotrue==0.2.0, but you have gotrue 0.5.0 which is incompatible.
supabase-py 0.0.2 requires postgrest-py==0.4.0, but you have postgrest-py 0.10.2 which is incompatible.

**Comment by dreinon** [comment]
The pypi package is called `supabase` instead of `supabase-py`, try installing the first.

De: ***@***.***>
Enviado: lunes, 23 de mayo de 2022 1:04
Para: ***@***.***>
CC: ***@***.***>
Asunto: [supabase-community/supabase-py] can you update these dependency (Issue #212)


Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

  1.  Go to '...'
  2.  Click on '....'
  3.  Scroll down to '....'
  4.  See error

Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

  *   OS: [e.g. iOS]
  *   Browser [e.g. chrome, safari]
  *   Version [e.g. 22]

Smartphone (please complete the following information):

  *   Device: [e.g. iPhone6]
  *   OS: [e.g. iOS8.1]
  *   Browser [e.g. stock browser, safari]
  *   Version [e.g. 22]

Additional context
Add any other context about the problem here.

supabase-py 0.0.2 requires gotrue==0.2.0, but you have gotrue 0.5.0 which is incompatible.
supabase-py 0.0.2 requires postgrest-py==0.4.0, but you have postgrest-py 0.10.2 which is incompatible.

**Comment by dreinon** [comment]
The pypi package is called `supabase` instead of `supabase-py`, try installing the first.
