### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by TBTech205** [supabase-community/supabase-py#303]
Hey all,

I am just wondering is anyone knows what this issue is. after getting every all setup and then I ran the code and I saw this (see the image bellow).

is there a way to turn this off. not sure where this is coming from

pls help

![image](https://user-images.githubusercontent.com/48381745/200143343-6be78d46-df3f-4785-ae1c-ab12f657dbc3.png)

Edit: I forgot to mention that this didn't happen before installing supabase

**Comment by anand2312** [comment]
Those logs look related to the Discord gateway and not supabase

**Comment by TBTech205** [comment]
this issue wasn't happening before installing supabase

**Comment by TBTech205** [comment]
config file
![image](https://user-images.githubusercontent.com/48381745/201496545-86db3b4d-9b24-4782-a527-b9fdeff48e66.png)

then i import this then run the bot this (image below) is there
![image](https://user-images.githubusercontent.com/48381745/201496609-af42b0ff-fdc2-49a4-a02a-43ccb6df2440.png)

**Comment by J0** [comment]
Hey,

do you mind sharing the relevant logging code? What logs are these again?

**Comment by PaveTranquil** [comment]
The same error is caught. When I use `aiogram` module and try to set logging to file, I set config by `logging.basicConfig`. But it doesn't work, because `supabase` did something with it. I change level to **DEBUG** and set the filename, but it changes back to **INFO** and to stdout. Need to fix and I don't know, how to do that.
