### ISSUE TITLE
Feature Request: upload files to Supabase Buckets

### ISSUE THREAD

**Issue by yuchdev** [supabase-community/supabase-py#316]
Looks like JS counterpart [offers automated upload](https://dev.to/aaronksaunders/how-to-upload-to-storage-buckets-and-write-data-with-remix-and-supabase-3l7c) to Supabase Storage buckets.
I could not find such a feature in the Python API.
Do we have plans to implement it?

**Comment by J0** [comment]
Hey @yuchdev,

We do have a ported `upload()` function.
This can be accessed by something like:
 
```python3
supa = supabase.storage()
res = supa.from_("<your-table-name>").upload(<file-name>)
```

We'll try to put together some docs soon but if you have any issues feel free to let us know

**Comment by MrTob** [comment]
how to fix this error?
` {'statusCode': 400, 'error': 'Invalid JWT', 'message': 'new row violates row-level security policy for table "objects"'}`

selecting data from tables does work....

**Comment by J0** [comment]
Hey @MrTob,

Apologies, missed this do you mind pasting the query you are trying to execute? Ah if you're trying to work with storage you'll also need to add the corresponding RLS policies on the storage/objects - see [the JS reference](https://supabase.com/docs/reference/javascript/storage-createbucket) for examples of policies which need to be added. This is so that you can restrict access to storage. Alternatively, if you are fine with the content being public you can set the bucket access to public.

Let me know if there are queries!

**Comment by MrTob** [comment]
Hi @J0 
Thanks for the quick reply

Currently my storage is public, in the future I would like to allow reading to all and write(upload) should only the Python program. Currently I use this code. unfortunately I get an empty list back. 

```python
supabase: Client = create_client(url, key)
storage = supabase.storage()
res = storage.list_buckets()
```
What am I doing wrong?

**Comment by J0** [comment]
Hey @MrTob 

There's an [upload function](https://github.com/supabase-community/storage-py/blob/main/storage3/_async/file_api.py#L198) implemented - do let me know if it meets your needs. 

Let me try and replicate the code above

**Comment by yuchdev** [comment]
Yes, seems like the feature is available. 
I'm closing the ticket

**Comment by J0** [comment]
Thanks! I'll try to document it soon but let me know if there are any issues
