### ISSUE TITLE
Specifying schema throws an error

### ISSUE THREAD

**Issue by altryne** [supabase-community/supabase-py#330]
**Describe the bug**
I want to specify the `auth` schema to look up users.
The default schema is public, so I want to instantiate a new client with "auth" schema

**To Reproduce**
`supabase: Client = create_client(url, key, options={'schema': 'auth'})` 

**Expected behavior**
a new supabaseclient with auth schema is loaded into `supabase` 

```    options.headers.update(self._get_auth_headers())
AttributeError: 'dict' object has no attribute 'headers'
```

For some reason it fails for something unrelated (headers)

**Comment by feliche93** [comment]
@altryne had the same error, were you able to solve it?

**Comment by altryne** [comment]
No, auth schema is not exposed via the client. 
I had to create a custom function and call it via .rpc

**Comment by feliche93** [comment]
Cool, thanks for the tip. Also figured it out and thought I might as well
just use the public schema then haha

**Comment by anand2312** [comment]
The error is because the `options` parameter is expected to be of type [`ClientOptions`](https://github.com/supabase-community/supabase-py/blob/202c070a94a4028c43eab0b3dcfb19a363dc92ae/supabase/lib/client_options.py#L14).
Passing an instance of ClientOptions with the schema parameter fixes the error, although as you've said the auth schema isn't exposed by Postgrest.
```ipython
In [3]: from supabase.lib.client_options import ClientOptions

In [6]: client = create_client(url, key, options=ClientOptions(schema="auth"))
```
