### ISSUE TITLE
Inconsistent results when using `eq`

### ISSUE THREAD

**Issue by koaning** [supabase-community/supabase-py#37]
# Bug report

## Describe the bug

I have a query that runs just as expected. 

```
> supabase.table("storage").select('*').ilike('message', 'dude').execute()
{'data': [{'id': 2,
   'inserted_at': '2021-07-27T18:34:27.084558+00:00',
   'updated_at': '2021-07-27T18:34:27.084558+00:00',
   'email': 'example@gmail.com',
   'message': 'dude'},
  {'id': 3,
   'inserted_at': '2021-07-27T18:34:31.482083+00:00',
   'updated_at': '2021-07-27T18:34:31.482083+00:00',
   'email': 'example@gmail.com',
   'message': 'dude'}],
 'status_code': 200}
```

But notice what happens when I run: 

```
> supabase.table("storage").select('*').like('email', 'example@gmail.com').execute()
{'data': [], 'status_code': 200}
```

Somehow I cannot query the email like I can the other columns in my table. Is `email` a protected value? 

I am using `supabase-py` version `0.0.2`.

**Comment by willtraweek** [comment]
I've been running into the same issue.  When I started playing around with it, it looked like the @ sign is the problem.

For example, when I set an email to `test` and execute the query with that value, then the row shows up just fine.

This may be because the email is encoded such that the `@` shows up as an `%40`.  Any advice from the supabase team here?

**Comment by willtraweek** [comment]
I'm beginning to think this is because they use a `.` to differentiate between the command and the query itself.  See the URL that `.eq("email", "test@test.com")` produces:
<img width="519" alt="Screen Shot 2021-08-09 at 12 40 36 PM" src="https://user-images.githubusercontent.com/4293967/128749817-2d1e9a74-d664-4b25-b15a-e5688a3c6e74.png">
