### ISSUE TITLE
[FEATURE] Add Logical OR operator to match at least one filter

### ISSUE THREAD

**Issue by fquellec** [supabase-community/supabase-py#548]
**Is your feature request related to a problem? Please describe.**
When performing a select operation It is currently not possible to match only rows which satisfy at least one of several filters. 

**Describe the solution you'd like**
Would be nice to implement the same operator than in the javascript client: https://supabase.com/docs/reference/javascript/or

**Describe alternatives you've considered**
One solution for now is to make several queries.. one per filter...

**Comment by J0** [comment]
Hey!

@fquellec Going to shift this over to [the postgrest-py](https://github.com/supabase-community/postgrest-py/issues/137) so we can track it there. It's been there for a while but looks like we might finally get to it.

Going to close this issue here but let me know if there are strong objections

Thanks for flagging!

**Comment by ad12** [comment]
@J0 thanks for the insight here! is this now available?
