### ISSUE TITLE
Is AsyncClient ready?

### ISSUE THREAD

**Issue by ToniRV** [supabase-community/supabase-py#686]
I see code for AsyncClient but it is not exposed in __init__.py
Is it supposed to be in development? Does it work?

**Comment by Atticuszz** [comment]
> I see code for AsyncClient but it is not exposed in __init__.py
> Is it supposed to be in development? Does it work?
> 
> 

Hey there👋,

The asynchronous code is essentially complete, but there might be some minor bugs since it was recently finished. It's primarily modeled after the synchronous client, so the main functionalities are stable and meet the requirements. 

However, the maintainer has been unavailable lately due to other commitments. 

I've added some options more suitable for backend development in my repository. 
Additionally, I've created a template for FASTA+supabase cuda, which you can find here: fastapi_supabase_template. This base template for FastAPI+Supabase comes with over 90% test coverage. 
I hope the existing tests and other code will be helpful💪.

**Comment by silentworks** [comment]
You can use the async client by importing it directly from its module. It's not available in the main module because that would be a breaking change in the library. The example below if from some FastAPI code I have.

```python
from supabase._async.client import AsyncClient as Client, create_client

async def create_supabase(request: Request) -> Client:
    return await create_client(
        url,
        key,
        options=ClientOptions(storage=FastApiSessionStorage(request.session)),
    )
```

**Comment by ToniRV** [comment]
Thank you guys, you both rock!

**Comment by taikon** [comment]
A bit confused on the two libraries. Should we be using supabase-py-async or supabase-py's AsyncClient?
