### ISSUE TITLE
Cannot order by multiple columns

### ISSUE THREAD

**Issue by justinsunyt** [supabase-community/supabase-py#775]
# Bug report

## Describe the bug

When trying to order multiple columns by using multiple .order() modifiers on a select function, the result only orders by the first column specified.

## To Reproduce

Here is my code to get some rows from a table, which is then ordered first by last_chatted and then by created_at.

```
response = (
    supabase.table("clones")
    .select("*")
    .eq("owner", uid)
    .order("last_chatted", desc=True)
    .order("created_at", desc=True)
    .execute()
)
```

## Expected behavior

The response should be ordered by last_chatted, and then created_at. However, this is not the case and the result is only ordered by last_chatted. I have confirmed that when I only order by last_chatted and created_at separately the code works as expected. I have also confirmed using the sort by visualization on my Supabase dashboard that the chained ordering is different from the result I get.

## System information

- OS: macOS
- supabase: 2.4.2

## Additional context

The same issue was reported in Discord in December, but no GitHub issue was created.

**Comment by silentworks** [comment]
Closing this out as there has been no reply in over a month.

**Comment by Nikdedov** [comment]
@justinsunyt 
Faced same problem, and the issue is with [postgrest-py](https://github.com/supabase/postgrest-py) not with supabase-py.
My workaround using your example:
`
request_build=
    supabase.table("clones")
    .select("*")
    .eq("owner", uid)
    .order("last_chatted", desc=True)
    .order("created_at", desc=True)

#get list of all added orders
removed_orders=request_build.params.get_list('order')

# remove them from QueryParams
request_build.params=request_build.params.remove('order')

#add back by merging them
request_build.params=request_build.params.add('order',','.join(removed_orders))
response =request_build.execute()
`
The problem is that adding several orders generates for QueryParams something like this: `&order=last_chatted.desc&order=created_at.desc` , but according to [postgrest docs](https://docs.postgrest.org/en/v12/references/api/tables_views.html) it should look like: `&order=last_chatted.desc,created_at.desc`

**Comment by pppdns** [comment]
In Typescript, you can do something like this:

```typescript
let query = supabase().from('your_table);

// Apply ordering as chained .order calls
for (const col of sortCriteria) {
  query = query.order(col);
}

const { data, error } = await query;
```

**Comment by vojtabohm** [comment]
Can confirm. It's indeed a bug. Stacking multiple .order() declarations yields an incorrect query passed into Postgres.

e.g. `.order("time_min", desc=True).order("id", desc=True)` 
yields
`&order=time_min.desc&order=id.desc`
instead of
`&order=time_min.desc,id.desc`

The workaround, as multiple people above suggest, is to manually fix it. I wrote a small utility:
```python
def columns(*cols: Tuple[str, bool]) -> str:
    if not cols:
        raise ValueError("At least one column must be specified")
    
    parts = [f"{col}.{'desc' if desc else 'asc'}" for col, desc in cols]
    return ",".join(parts)
```
at call site:
`query.order(columns(("time_min", desc), ("id", desc)))`

@silentworks can we reopen this, as it is a reproducible, unsolved issue?
